### ISSUE TITLE
Is the curve data in the CYZ file filtered or unfiltered?

### ISSUE THREAD

**Issue by RobBlackwell** [Cytobuoy/CyzFile-API#3]
In the CytoClus Analysis Equations documentation, it says that "Before data is analyzed in CytoClus, it is filtered".  Please would you clarify whether the data that we read from CYZ using CyzFile-API is filtered or unfiltered? i.e., has the weighted average algorithm already been applied, please?

**Comment by LievaartR** [comment]
The filter is always applied before calculating the parameters.  Also when you retrieve the actual particle pulse shapes from the file, the filtering is applied as well.  It is possible to get the raw unfiltered pulse shapes if you want, the array:

```
p.ChannelData(chnIdx).Data_mV_unsmoothed
```

Will contain the pulse shape data before applying the filter.

**Comment by RobBlackwell** [comment]
Thank you!
