### ISSUE TITLE
How do we get corespeed from the API ?

### ISSUE THREAD

**Issue by LucindaLanoy** [Cytobuoy/CyzFile-API#4]
We're trying to calculate the Length as described in the CytoClus Analysis Equations document, it mentions the `corespeed` variable but we aren't certain how to determine `corespeed` from the API. We know that CytoClus4 can display the `corespeed` in the metadata file, but how can we determine that using the API ?

**Comment by LievaartR** [comment]
Hi,

The corespeed can be retrieved from the file using:

```
DataFileWrapper dfw = new DataFileWrapper(filename);
dfw.CytoSettings.SampleCorespeed
```


This property (and many others) can be found in the file ```CytoSettings\CytoSenseSettings.vb```

**Comment by LucindaLanoy** [comment]
Thank you
